artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gowtham-dd/Datasets/raw/main/DNA_Sequence.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  data_path: artifacts/data_ingestion/DNA_Sequence/trainYX.csv 


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/DNA_Sequence/trainYX.csv 
  transformed_features_path: artifacts/data_transformation/X.npy
  transformed_labels_path: artifacts/data_transformation/y.npy

model_trainer:
  root_dir: artifacts/model_trainer
  transformed_data_dir: artifacts/data_transformation
  model_dir: artifacts/model_trainer/models


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/X.npy
  test_labels_path: artifacts/data_transformation/y.npy
  model_dir: artifacts/model_trainer/models
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: "https://dagshub.com/gowtham-dd/DNAseqMLOPS.mlflow"  # Your MLflow tracking URI